# Multiple dispatch

In [1]:
*

* (generic function with 309 methods)

In [3]:
# methods(*)

In [4]:
mat1 = reshape(Vector(1:12),(3,4))

3×4 Matrix{Int64}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [6]:
mat2 = reshape(Vector(11:22),(4,3))

4×3 Matrix{Int64}:
 11  15  19
 12  16  20
 13  17  21
 14  18  22

In [7]:
*(mat1, mat2)

3×3 Matrix{Int64}:
 290  378  466
 340  444  548
 390  510  630

In [9]:
*("Julia", "Python")

"JuliaPython"

In [10]:
f(x::Float64, y::Float64) = x^2 + y^2

f (generic function with 1 method)

In [11]:
f(3.0, 6.0)

45.0

In [12]:
f(3,6)

LoadError: MethodError: no method matching f(::Int64, ::Int64)

In [13]:
f(x::Int64, y::Int64) = x^2 + y^2

f (generic function with 2 methods)

In [14]:
f(3,6)

45

In [15]:
f(3.0,6.0)

45.0

In [16]:
f(x::Number, y::Number) = x^2 - y^2

f (generic function with 3 methods)

In [17]:
f(3.0,4)

-7.0

In [18]:
methods(f)

# 3 methods for generic function "f" from Main:
 [1] f(x::Float64, y::Float64)
     @ In[10]:1
 [2] f(x::Int64, y::Int64)
     @ In[13]:1
 [3] f(x::Number, y::Number)
     @ In[16]:1

In [21]:
f(x::Any, y::Any) = "This is not correct"

f (generic function with 4 methods)

In [22]:
f("Hemanth",5)

"This is not correct"

In [23]:
methods(f)

# 4 methods for generic function "f" from Main:
 [1] f(x::Float64, y::Float64)
     @ In[10]:1
 [2] f(x::Int64, y::Int64)
     @ In[13]:1
 [3] f(x::Number, y::Number)
     @ In[16]:1
 [4] f(x, y)
     @ In[21]:1

In [24]:
g(x::Int64, y) = x*y
g(x, y::Int64) = x/y

g (generic function with 2 methods)

In [26]:
g(2,3.0)

6.0

In [27]:
g(2.0,3)

0.6666666666666666

In [28]:
g(2,3) # Method can't decide which function to call

LoadError: MethodError: g(::Int64, ::Int64) is ambiguous.

Candidates:
  g(x::Int64, y)
    @ Main In[24]:1
  g(x, y::Int64)
    @ Main In[24]:2

Possible fix, define
  g(::Int64, ::Int64)


In [29]:
# case 3
h(x=3, y=4) = x+y

h (generic function with 3 methods)

In [30]:
h(x::Int64, y::Int64) = x-y

h (generic function with 4 methods)

In [31]:
h() # optional arguments are tied to the function

-1

In [32]:
methods(h)

# 4 methods for generic function "h" from Main:
 [1] h()
     @ In[29]:2
 [2] h(x::Int64, y::Int64)
     @ In[30]:1
 [3] h(x)
     @ In[29]:2
 [4] h(x, y)
     @ In[29]:2

# Parametric methods

In [1]:
test_types(x::T, y::T) where {T} = "Arguments have the same type"

test_types (generic function with 1 method)

In [2]:
test_types(4,5)

"Arguments have the same type"

In [3]:
test_types(5.6,4.3)

"Arguments have the same type"

In [4]:
test_types("abc","bcd")

"Arguments have the same type"

In [5]:
test_types(5,3.2) # we will get error

LoadError: MethodError: no method matching test_types(::Int64, ::Float64)

Closest candidates are:
  test_types(::T, ::T) where T
   @ Main In[1]:1


In [6]:
test_types(x,y) = "Argument types are different"

test_types (generic function with 2 methods)

In [7]:
test_types(5,3.2)

"Argument types are different"

In [8]:
find_type(x::T) where {T} = T

find_type (generic function with 1 method)

In [9]:
find_type(3)

Int64

In [10]:
find_type(5.6)

Float64

In [11]:
find_type(:Hello)

Symbol

In [12]:
test_types_number(x::T, y::T) where {T <: Number} = "Same type numbers!"

test_types_number (generic function with 1 method)

In [14]:
test_types_number(3,5)

"Same type numbers!"

In [15]:
test_types_number(3.4,5.2)

"Same type numbers!"

In [16]:
test_types_number(3, 7.7) # numbers are different types

LoadError: MethodError: no method matching test_types_number(::Int64, ::Float64)

Closest candidates are:
  test_types_number(::T, ::T) where T<:Number
   @ Main In[12]:1


In [17]:
test_types_number(x::Number, y::Number) = "Both numbers but different types"

test_types_number (generic function with 2 methods)

In [18]:
test_types_number(4,5.5)

"Both numbers but different types"

In [19]:
test_types_number(4,"abc") # won't work

LoadError: MethodError: no method matching test_types_number(::Int64, ::String)

Closest candidates are:
  test_types_number(::T, ::T) where T<:Number
   @ Main In[12]:1
  test_types_number(::Number, ::Number)
   @ Main In[17]:1


In [20]:
test_type_number(x,y) = "At least one argument is not number"

test_type_number (generic function with 1 method)

In [21]:
test_type_number("abc",5)

"At least one argument is not number"

In [22]:
test_type_number("abc","Hello")

"At least one argument is not number"

In [23]:
test_type_number(4,5)

"At least one argument is not number"

In [24]:
find_type(x::T, y::P) where {T <: String, P <: Number} = "$x is String and $y is Number"

find_type (generic function with 2 methods)

In [25]:
find_type("Hemanth", 5)

"Hemanth is String and 5 is Number"

In [26]:
find_type(5, "Hemanth") # error

LoadError: MethodError: no method matching find_type(::Int64, ::String)

Closest candidates are:
  find_type(::T) where T
   @ Main In[8]:1


In [27]:
check_types(a::Array{T}, x::T) where {T} = "$x has the same type with the array."

check_types (generic function with 1 method)

In [28]:
check_types(Vector(1:15), 20)

"20 has the same type with the array."

In [29]:
# custom parametric methods

In [30]:
abstract type Shape end

In [34]:
struct Circle <: Shape
    radius::Float64
end

In [35]:
struct Rectangle <: Shape
    width::Float64
    height::Float64
end

In [37]:
area(s::Circle) = π * s.radius^2
area(s::Rectangle) = s.width * s.height

area (generic function with 2 methods)

In [38]:
rectangle = Rectangle(3.5, 9.6)

Rectangle(3.5, 9.6)

In [39]:
circ = Circle(6.4)

Circle(6.4)

In [40]:
area(rectangle)

33.6

In [41]:
area(circ)

128.67963509103794

In [42]:
Base.show(io::IO, s::Shape) = println(io, "Shape: ",typeof(s), ", Area: ",area(s))

In [44]:
rectangle

Shape: Rectangle, Area: 33.6


In [45]:
circ

Shape: Circle, Area: 128.67963509103794


In [46]:
# restrict number of arguments

In [47]:
two_args(x::Vararg{Number, 2}) = maximum(x)

two_args (generic function with 1 method)

In [48]:
two_args(1,2)

2

In [49]:
two_args(1) # passing only 1 arg

LoadError: MethodError: no method matching two_args(::Int64)

Closest candidates are:
  two_args(::Number, ::Number)
   @ Main In[47]:1


In [50]:
two_args(1,2,3) # passing more than 2 args

LoadError: MethodError: no method matching two_args(::Int64, ::Int64, ::Int64)

Closest candidates are:
  two_args(::Number, ::Number)
   @ Main In[47]:1


# Function like Objects

In [51]:
mutable struct model{R}
    coefficients::Vector{R}
end

In [56]:
function (m::model)(x)
    coeffis = m.coefficients
    s = 0
    for i in 1:length(x)
        s+=x[i]*coeffis[i]
    end
    return s
end

In [57]:
lm = model([1, 3, 5]) # do not give matrix

model{Int64}([1, 3, 5])

In [58]:
lm([2, 4, 6])

44

# constructors

In [60]:
mutable struct ModelVars
    x₁::Float64 # \_1 TAB
    x₂::Float64
    x₃::Float64
end

In [61]:
fieldnames(ModelVars)

(:x₁, :x₂, :x₃)

In [62]:
m1 = ModelVars(2.5,5.6,7.8)

ModelVars(2.5, 5.6, 7.8)

In [63]:
m1.x₁

2.5

In [64]:
methods(ModelVars)

# 2 methods for type constructor:
 [1] ModelVars(x₁::Float64, x₂::Float64, x₃::Float64)
     @ In[60]:2
 [2] ModelVars(x₁, x₂, x₃)
     @ In[60]:2

In [66]:
ModelVars(3,5,7)

ModelVars(3.0, 5.0, 7.0)

In [68]:
m1.x₁ = 3.5 # since the struct is mutable

3.5

In [69]:
m1.x₁

3.5

In [70]:
abstract type Student end

In [71]:
Student()

LoadError: MethodError: no constructors have been defined for Student

In [73]:
mutable struct CSSStudent <: Student
    name::String
    student_id::Int64
    gpa::Float64
    specialization::String
    programming_language::String
end

In [74]:
cs1 = CSSStudent("George",12344,3.75,"Data Science","Julia")

CSSStudent("George", 12344, 3.75, "Data Science", "Julia")

In [75]:
CSSStudent(name, id, gpa) = CSSStudent(name, id, gpa, "Data Science","Julia")

CSSStudent

In [76]:
methods(CSSStudent)

# 3 methods for type constructor:
 [1] CSSStudent(name::String, student_id::Int64, gpa::Float64, specialization::String, programming_language::String)
     @ In[73]:2
 [2] CSSStudent(name, id, gpa)
     @ In[75]:1
 [3] CSSStudent(name, student_id, gpa, specialization, programming_language)
     @ In[73]:2

In [77]:
CSSStudent("Mary",112233,3.95)

CSSStudent("Mary", 112233, 3.95, "Data Science", "Julia")

In [78]:
CSSStudent("Ali",12345,3.11,"Development","Java")

CSSStudent("Ali", 12345, 3.11, "Development", "Java")

In [79]:
mutable struct DataScienceStudent <: CSSStudent end # can't do this

LoadError: invalid subtyping in definition of DataScienceStudent: can only subtype abstract types.

In [83]:
function CSSStudent(; name, student_id, gpa=NaN, specialization="Data Science", programming_language="Julia")
    return CSSStudent(name, student_id, gpa, specialization, programming_language)
end




CSSStudent

In [85]:
methods(CSSStudent)

# 4 methods for type constructor:
 [1] CSSStudent(; name, student_id, gpa, specialization, programming_language)
     @ In[83]:1
 [2] CSSStudent(name::String, student_id::Int64, gpa::Float64, specialization::String, programming_language::String)
     @ In[73]:2
 [3] CSSStudent(name, id, gpa)
     @ In[75]:1
 [4] CSSStudent(name, student_id, gpa, specialization, programming_language)
     @ In[73]:2

In [84]:
CSSStudent(name="Mario", student_id=234533, specilization="Mobile Development", programming_language="Kotlin") # somehow this is not working

LoadError: MethodError: no method matching CSSStudent(; name::String, student_id::Int64, specilization::String, programming_language::String)

Closest candidates are:
  CSSStudent(; name, student_id, gpa, specialization, programming_language) got unsupported keyword argument "specilization"
   @ Main In[83]:1
  CSSStudent(::String, ::Int64, ::Float64, ::String, ::String) got unsupported keyword arguments "name", "student_id", "specilization", "programming_language"
   @ Main In[73]:2
  CSSStudent(::Any, ::Any, ::Any) got unsupported keyword arguments "name", "student_id", "specilization", "programming_language"
   @ Main In[75]:1
  ...


In [86]:
students = CSSStudent[]

CSSStudent[]

In [87]:
push!(students, cs1)

1-element Vector{CSSStudent}:
 CSSStudent("George", 12344, 3.75, "Data Science", "Julia")

In [88]:
students

1-element Vector{CSSStudent}:
 CSSStudent("George", 12344, 3.75, "Data Science", "Julia")

In [90]:
mutable struct MathStudent
    name::String
    student_id::Int64
    gpa::Float64
    MathStudent(name, student_id, gpa) = gpa < 0 ? throw("gpa cannot be negative") : new(name, student_id, gpa)
end

In [91]:
m1 = MathStudent("karl", 111222, 3.4)

MathStudent("karl", 111222, 3.4)

In [92]:
m2 = MathStudent("Hemanth",232435, -3.2) # it shoud throw our custom error

LoadError: "gpa cannot be negative"

In [93]:
# user should always enter correct values else get error

In [95]:
mutable struct EconStudent
    name::String
    student_id::Int64
    gpa::Float64
    
    function EconStudent(name, student_id, gpa)
        if name == ""
            throw("Student name cannot be empty")
        elseif student_id == NaN || student_id == 0
            throw("Student ID cannot be empty")
        elseif gpa<0 || gpa >4.0
            throw("Enter valid gpa")
        else
            new(name, student_id, gpa)
        end
    end
end

In [96]:
esq = EconStudent("",1234,3.2)

LoadError: "Student name cannot be empty"

In [97]:
es2 = EconStudent("Hemanth",0,3.2)

LoadError: "Student ID cannot be empty"

In [98]:
es3 = EconStudent("Hemanth",234454, 5)

LoadError: "Enter valid gpa"

In [99]:
es4 = EconStudent("Hemanth",23544,3.2)

EconStudent("Hemanth", 23544, 3.2)

In [100]:
mutable struct PhysStudent <: Student
    name::String
    student_id::Int64
    gpa::Float64
    
    PhysStudent() = new()
end

In [101]:
ps1 = PhysStudent()

PhysStudent(#undef, 1472292817360, 0.0)

In [103]:
methods(PhysStudent)

# 1 method for type constructor:
 [1] PhysStudent()
     @ In[100]:6

In [107]:
mutable struct Course
    name::String
    student::Array{Union{CSSStudent, MathStudent, EconStudent}, 1}
    opened::Bool
    
    Course(name::String) = new(name::String, String[], false)
    Course(name::String, members) = new(name, members, length(members)>=5)
end

In [108]:
methods(Course)

# 2 methods for type constructor:
 [1] Course(name::String)
     @ In[107]:6
 [2] Course(name::String, members)
     @ In[107]:7

In [109]:
Julia101 = Course("Programming with Julia", [cs1])

Course("Programming with Julia", Union{CSSStudent, EconStudent, MathStudent}[CSSStudent("George", 12344, 3.75, "Data Science", "Julia")], false)