# Functions

In [2]:
# write function with return statement similar to python
function sum(x,y)
    return x+y
end

sum (generic function with 1 method)

In [3]:
sum(3,4)

7

In [4]:
# In Julia we can also write function without return statement
function sum(x,y)
    x+y
end

sum (generic function with 1 method)

In [5]:
sum(7,6)

13

In [6]:
# we can also write single line functions like this
sum(x,y) = x+y

sum (generic function with 1 method)

In [7]:
sum(4,5)

9

In [9]:
# we can return multiple values similar to python
function multi_func(x,y)
    return x,y
end

multi_func (generic function with 1 method)

In [11]:
a,b = multi_func(2,3)

(2, 3)

In [12]:
a

2

In [13]:
b

3

In [14]:
# using unicode characters as function names
# \Phi TAB
function Φ(x,y)
    x+y
end

Φ (generic function with 1 method)

In [15]:
Φ(3,4)

7

In [18]:
# using unicode characters as function names
# \sum TAB
function ∑(x,y)
    x+y
end

∑ (generic function with 1 method)

In [20]:
∑(3,4)

7

In [21]:
# we can also specify datatype in argument
function fact(n::Integer)
    f = 1
    for i ∈ 1:n
        f *= i
    end
    return f
end

fact (generic function with 1 method)

In [23]:
fact(3)

6

In [24]:
# we can also specify datatype in argument
# we can also define the type of the return value
function fact(n::Integer)::Integer
    f = 1
    for i ∈ 1:n
        f *= i
    end
    return f
end

fact (generic function with 1 method)

In [25]:
fact(3)

6

In [26]:
# we can use operators as functions
*(3,4,5)

60

In [27]:
m = *
m(3,4,5)

60

In [29]:
function findmeansd(array)
    total = 0
    n = 0
    
    for el in array
        total += el
        n += 1
    end
    μ = total / n
    
    σ = 0
    for el in array
        σ += (el - μ)^2
    end
    σ = √(σ/(n-1))
    
    return μ, σ
end

findmeansd (generic function with 1 method)

In [30]:
findmeansd([1 2 3 4 5 6])

(3.5, 1.8708286933869707)

In [31]:
avg, sd = findmeansd([1 2 3 4 5 6])

(3.5, 1.8708286933869707)

In [32]:
# Anonymous functions
# we can also declare functions in below way
x -> 3x^2 + 5x - 4

#3 (generic function with 1 method)

In [36]:
g = x -> 3x^2 + 5x - 4

#5 (generic function with 1 method)

In [37]:
g(3)

38

In [38]:
(x,y,z) -> (x^2 - y^3)/z^3

#7 (generic function with 1 method)

In [41]:
# recursive functions
# factorial f an integer
fact(n) = n == 1 ? n : n* fact(n-1)

fact (generic function with 2 methods)

In [42]:
fact(3)

6

In [43]:
# recirsive functions example 2
# fibonachi
fibo(n) = n < 2 ? n : fibo(n-1) + fibo(n-2)

fibo (generic function with 1 method)

In [44]:
fibo(10)

55

# Map

In [46]:
# square of numbers traditional way
arr = [1 2 3 4 5 6]
sqrarr = []

for el in arr
    append!(sqrarr, el^2)
end

print(sqrarr)

Any[1, 4, 9, 16, 25, 36]

In [49]:
# same thing we can achieve using map function
arr = [1 2 3 4 5 6]
sqarr = map(x -> x^2, arr)
print(sqarr)

[1 4 9 16 25 36]

In [50]:
# map is almost equal to broadcast
arr = [1 2 3 4 5 6]
sqarr = broadcast(x -> x^2, arr)
print(sqarr)

[1 4 9 16 25 36]

In [51]:
rowvec = [1 2 3 4 5]
colvec = [10 20 3 40 50]

map(+, rowvec, colvec)

1×5 Matrix{Int64}:
 11  22  6  44  55

In [52]:
# same as above
rowvec .+ colvec

1×5 Matrix{Int64}:
 11  22  6  44  55

# reduce

In [53]:
# sum of all the numbers
arr = [1 2 3 4 5 6]
reduce(+, arr)

21

In [54]:
# we can also do map and reduce both at once
sqarr = map(x -> x^2, arr)
sumsqr = reduce(+, sqarr)

91

In [55]:
# we can do the same using maoreduce
mapreduce(x -> x^2, +, arr)

91

# filter

In [56]:
arr = [1 2 3 4 5 6]
filter(x -> x%4 == 0, arr)

1-element Vector{Int64}:
 4

### example 1

In [58]:
struct Course
    subject::Symbol
    field::Symbol
    ncourses::Int
    nstudents::Int # average number of students in a course
end

In [59]:
coursedata = [Course(:Julia, :Programming, 10, 25), Course(:Python, :Programming, 12, 30), Course(:Mathematics, :Science, 30, 100), Course(:Physics, :Science, 45, 300) ]

4-element Vector{Course}:
 Course(:Julia, :Programming, 10, 25)
 Course(:Python, :Programming, 12, 30)
 Course(:Mathematics, :Science, 30, 100)
 Course(:Physics, :Science, 45, 300)

In [60]:
nprogramming = filter(x -> x.field == :Programming, coursedata)

2-element Vector{Course}:
 Course(:Julia, :Programming, 10, 25)
 Course(:Python, :Programming, 12, 30)

In [61]:
nprogramming = filter(x -> x.field === :Programming, coursedata)

2-element Vector{Course}:
 Course(:Julia, :Programming, 10, 25)
 Course(:Python, :Programming, 12, 30)

In [65]:
nstudents = map(x -> x.ncourses * x.nstudents, nprogramming)

2-element Vector{Int64}:
 250
 360

In [66]:
totalstudents = reduce(+, nstudents)

610

In [67]:
# We can so all the above operations in function
function nfield(data, field)
    f = filter(x -> x.field === field, data)
    nstud = map(x -> x.ncourses * x.nstudents, f)
    totalstudents = reduce(+, nstudents)
    return totalstudents
end

nfield (generic function with 1 method)

In [73]:
# We can write the same above function as below
function nfield(data, field)
    f = filter(x -> x.field === Symbol(field), data)
    s = mapreduce(x -> x.ncourses * x.nstudents,+, f)
    return s
end

nfield (generic function with 1 method)

In [74]:
nfield(coursedata, :Science)

16500

In [75]:
nfield(coursedata, "Science")

16500

In [91]:
function f(x)
    if (x % 2 == 0) # here the brackets are very important
        return "Div by 2"
    else
        return "Not Div by 2"
    end
end

f (generic function with 1 method)

In [93]:
arr = [1 2 3 4 5]
map(f, arr)

1×5 Matrix{String}:
 "Not Div by 2"  "Div by 2"  "Not Div by 2"  "Div by 2"  "Not Div by 2"

In [94]:
# we can do the same with anonymous function, but not very good looking
map(x -> begin
        if (x % 2 == 0) # here the brackets are very important
        return "Div by 2"
        else
            return "Not Div by 2"
        end
    end, arr)

1×5 Matrix{String}:
 "Not Div by 2"  "Div by 2"  "Not Div by 2"  "Div by 2"  "Not Div by 2"

In [95]:
# but we can achieve the same using do keyword
map(arr) do x
    if (x % 2 == 0) # here the brackets are very important
        return "Div by 2"
    else
        return "Not Div by 2"
    end
end

1×5 Matrix{String}:
 "Not Div by 2"  "Div by 2"  "Not Div by 2"  "Div by 2"  "Not Div by 2"

In [96]:
# this do is very similar to "with" in python
data = "Programming with Julia. \n Higher order functions. \n Map, reduce and filter"

open("input.txt","w+") do io
    write(io, data)
end

74

## Variable arguments

In [97]:
# This is very similar to *args, **kwargs in python

In [98]:
varfunc(x...) = (x)

varfunc (generic function with 1 method)

In [99]:
varfunc(2,3)

(2, 3)

In [100]:
varfunc(2,3,4,5)

(2, 3, 4, 5)

In [101]:
function printall(x...)
    println(x)
end

printall (generic function with 1 method)

In [102]:
printall("Julia")

("Julia",)


In [103]:
printall("Julia","Python")

("Julia", "Python")


In [107]:
# sum of all arguments
# if we send more than 2 arguments then the below function will be called
addall(x, y...) = x + addall(y...)

# if we send only 1 argument then the below function will be called
addall(x) = x

# this is not possible in python

addall (generic function with 2 methods)

In [105]:
addall(7)

7

In [106]:
addall(7,8)

15

In [109]:
# find minimum of 2 numbers
findmini(x,y) = x < y ? x : y

findmini (generic function with 1 method)

In [112]:
# find minimum of multiple numbers
findmini(x, y...) = findmini(x, findmini(y...))

findmini (generic function with 2 methods)

In [113]:
findmini(4,1,-5,17,7)

-5

In [114]:
a, b, c... = [3,4,5,6,7,8]

6-element Vector{Int64}:
 3
 4
 5
 6
 7
 8

In [115]:
a

3

In [116]:
b

4

In [117]:
c

4-element Vector{Int64}:
 5
 6
 7
 8

In [118]:
function printtype(args...)
    for i in args
        println(typeof(i))
    end
end

printtype (generic function with 1 method)

In [120]:
printtype(4,"hemanth",:Programming)

Int64
String
Symbol


In [121]:
# splatting
(1:10...,)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [122]:
function printargs(a,b,c)
    println(a)
    println(b)
    println(c)
end

printargs (generic function with 1 method)

In [123]:
printargs("a","b","c")

a
b
c


In [124]:
tpl = ("a","b","c")

("a", "b", "c")

In [125]:
printargs(tpl)

LoadError: MethodError: no method matching printargs(::Tuple{String, String, String})

Closest candidates are:
  printargs(::Any, ::Any, ::Any)
   @ Main In[122]:1


In [126]:
# using ... we can split arguments
printargs(tpl...)

a
b
c


#### Optional arguments

In [128]:
function sum(a=0, b=0)
    return a+b
end

sum (generic function with 3 methods)

In [129]:
sum()

0

In [130]:
sum(3,4)

7

#### Keyword arguments

In [132]:
function positionargs(x, y=1, z=20, t=30)
    println("x = $x")
    println("y = $y")
    println("z = $z")
    println("t = $t")
end

positionargs (generic function with 4 methods)

In [134]:
positionargs(2)

x = 2
y = 1
z = 20
t = 30


In [133]:
positionargs(2,3,4,5)

x = 2
y = 3
z = 4
t = 5


In [135]:
positionargs(x=2) # this should not give error in python

LoadError: MethodError: no method matching positionargs(; x::Int64)

Closest candidates are:
  positionargs(::Any) got unsupported keyword argument "x"
   @ Main In[132]:1
  positionargs(::Any, ::Any) got unsupported keyword argument "x"
   @ Main In[132]:1
  positionargs(::Any, ::Any, ::Any) got unsupported keyword argument "x"
   @ Main In[132]:1
  ...


In [136]:
# keywordargs
function keywordargs(x; y=1, z=20, t=30)
    println("x = $x")
    println("y = $y")
    println("z = $z")
    println("t = $t")
end

keywordargs (generic function with 1 method)

In [137]:
keywordargs(2)

x = 2
y = 1
z = 20
t = 30


In [140]:
keywordargs(2, z=11)

x = 2
y = 1
z = 11
t = 30


In [141]:
keywordargs(2, t=12)

x = 2
y = 1
z = 20
t = 12


In [142]:
keywordargs(2; t=12)

x = 2
y = 1
z = 20
t = 12


# Composite functions

In [175]:
x = rand(-10:10,20);
squar(x) = x.^2;
function mysum(arr)
    s = 0
    for i ∈ arr
        s += i
    end
    return s
end

mysum (generic function with 1 method)

In [176]:
(mysum ∘ squar)(x)

879

In [177]:
# you can write the same as below
mysum(squar(x))

879

In [178]:
# you can write the same using | operator
x |> squar |> mysum

879

In [179]:
# find number of words in a string
str = "Writing functions in Julia Proframming is fun"
str |> split |> length

7

In [180]:
# find number of letters in each word in a string
str = "Writing functions in Julia Proframming is fun"
str |> split .|> length

7-element Vector{Int64}:
  7
  9
  2
  5
 11
  2
  3

In [4]:
# root mean square error
actual = [23 28 26 24 22]
predicted = [23 26 23 24 22]

1×5 Matrix{Int64}:
 23  26  23  24  22

In [6]:
sum(((actual - predicted) ./ length(actual)) .^2)

0.52

In [1]:
# Define your array
my_array = [1, 2, 3, 4, 5]

# Calculate the sum of all elements in the array
array_sum = sum(my_array)

# Display the result
println("Sum of the array: ", array_sum)


Sum of the array: 15


# Mutating function

In [11]:
x = [35, 76, -43, -36, 12, 3, 24, -45]

8-element Vector{Int64}:
  35
  76
 -43
 -36
  12
   3
  24
 -45

In [12]:
sort(x)

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [13]:
# x is not changed
x

8-element Vector{Int64}:
  35
  76
 -43
 -36
  12
   3
  24
 -45

In [14]:
# mutating function will change the x
sort!(x)

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [15]:
# x is changed
x

8-element Vector{Int64}:
 -45
 -43
 -36
   3
  12
  24
  35
  76

In [16]:
function padwithzeros(vector, n)
    x = [zeros(n); vector; zeros(n)]
    return x
end

padwithzeros (generic function with 1 method)

In [17]:
x = [35, 76, -43, -36, 12, 3, 24, -45]
padwithzeros(x, 3)

14-element Vector{Float64}:
   0.0
   0.0
   0.0
  35.0
  76.0
 -43.0
 -36.0
  12.0
   3.0
  24.0
 -45.0
   0.0
   0.0
   0.0

In [18]:
# x is still same
x

8-element Vector{Int64}:
  35
  76
 -43
 -36
  12
   3
  24
 -45

In [21]:
function padwithzeros!(vector, n)
    for i in 1:n
        insert!(vector,1,0)
    end
    
    for i in 1:n
        append!(vector, 0)
    end
end

padwithzeros! (generic function with 1 method)

In [22]:
padwithzeros!(x, 3)

In [23]:
# x has changed
x

14-element Vector{Int64}:
   0
   0
   0
  35
  76
 -43
 -36
  12
   3
  24
 -45
   0
   0
   0