# Tuples

In [1]:
# Tuples same as in python

In [2]:
tpl = (3,"Julia",2.3)

(3, "Julia", 2.3)

In [3]:
typeof(tpl)

Tuple{Int64, String, Float64}

In [4]:
t1 = tuple(2,3,4)

(2, 3, 4)

In [5]:
typeof(t1)

Tuple{Int64, Int64, Int64}

In [6]:
# there is difference in tuple and Tuple

In [7]:
supertype(Tuple)

Any

In [8]:
t2 = 2,3,4

(2, 3, 4)

In [9]:
typeof(t2)

Tuple{Int64, Int64, Int64}

In [10]:
t3 = (3)

3

In [11]:
typeof(t3)

Int64

In [12]:
t3 = (3,)

(3,)

In [13]:
typeof(t3)

Tuple{Int64}

In [14]:
# slicing tuples same as in python but index start with 1 unlike 0 in python

In [16]:
t1

(2, 3, 4)

In [17]:
t1[1]

2

In [18]:
t1[2]

3

In [19]:
t1[1:2]

(2, 3)

In [20]:
t1[1:3]

(2, 3, 4)

In [22]:
t1[2:3]

(3, 4)

In [23]:
# names tuples

In [24]:
t4 = (name="Hemanth", role="Data Scientist")

(name = "Hemanth", role = "Data Scientist")

In [25]:
t4.name

"Hemanth"

In [26]:
#  either you should name all or not

In [28]:
t4[name] # you can't do this

LoadError: UndefVarError: `name` not defined

In [29]:
t5 = (1,2,3)

(1, 2, 3)

In [30]:
a,b,c = t5

(1, 2, 3)

In [31]:
a

1

In [32]:
b

2

In [33]:
c

3

In [34]:
typeof(t5)

Tuple{Int64, Int64, Int64}

In [35]:
nt = (3,4,5,6) # creation of n tupes (tuples with all the same types)

(3, 4, 5, 6)

In [36]:
typeof(nt)

NTuple{4, Int64}

In [39]:
ntuple(x -> x^3,5)

(1, 8, 27, 64, 125)

In [40]:
# check wether element in tuple
in(3, nt)

true

In [41]:
3 ∈ nt # \in TAB

true

In [42]:
"C++" ∈ nt

false

In [43]:
# opposite of in (not in)
"c++" ∉ nt # \notin TAB

true

# dictionaries

In [45]:
d1 = Dict() # exmpty dictionary

Dict{Any, Any}()

In [46]:
studentgrades = Dict([("Hemanth",98),("Suresh",87),("Jyostna", 80)])

Dict{String, Int64} with 3 entries:
  "Jyostna" => 80
  "Suresh"  => 87
  "Hemanth" => 98

In [49]:
studentgrades["Hemanth"]

98

In [50]:
studentgrades = Dict("Hemanth" => 98, "Suresh" => 87, "Jyostna" => 80)

Dict{String, Int64} with 3 entries:
  "Jyostna" => 80
  "Suresh"  => 87
  "Hemanth" => 98

In [51]:
studentgrades["Hemanth"]

98

In [52]:
# add new element to dictionary

In [53]:
studentgrades["Ravi"] = 85

85

In [54]:
studentgrades

Dict{String, Int64} with 4 entries:
  "Jyostna" => 80
  "Suresh"  => 87
  "Hemanth" => 98
  "Ravi"    => 85

In [55]:
studentgrades[1] # can't do this

LoadError: KeyError: key 1 not found

In [58]:
length(studentgrades)

4

In [56]:
studentgrades.keys # don't use this

16-element Vector{String}:
 #undef
    "Jyostna"
 #undef
 #undef
 #undef
    "Suresh"
 #undef
    "Hemanth"
    "Ravi"
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [57]:
studentgrades.vals # don't use this

16-element Vector{Int64}:
               0
              80
   1648874192992
               0
 140726959337488
              87
               0
              98
              85
               0
 140727037242976
 140727037251152
               0
 140727037242976
 140727037251152
               0

In [59]:
keys(studentgrades)

KeySet for a Dict{String, Int64} with 4 entries. Keys:
  "Jyostna"
  "Suresh"
  "Hemanth"
  "Ravi"

In [60]:
values(studentgrades)

ValueIterator for a Dict{String, Int64} with 4 entries. Values:
  80
  87
  98
  85

In [62]:
# check keys
"Hemanth" ∈ keys(studentgrades)

true

In [65]:
haskey(studentgrades, "Hemanth") # same as above

true

In [63]:
# check values
87 ∈ values(studentgrades)

true

In [67]:
# When I search for Key in dictionary if the key not found I want a default message

In [68]:
get(studentgrades, "Hemanth", "Not found")

98

In [69]:
get(studentgrades, "Raghu", "Not found")

"Not found"

In [70]:
# if the key not found then assign a value

In [72]:
get!(studentgrades, "Raghu", 85)

85

In [73]:
studentgrades

Dict{String, Int64} with 5 entries:
  "Jyostna" => 80
  "Raghu"   => 85
  "Suresh"  => 87
  "Hemanth" => 98
  "Ravi"    => 85

In [74]:
# only get key else give a message

In [76]:
getkey(studentgrades, "Hemanth", "Not found")

"Hemanth"

In [77]:
getkey(studentgrades, "Ram", "Not found")

"Not found"

In [78]:
# delete a key

In [79]:
delete!(studentgrades, "Raghu")

Dict{String, Int64} with 4 entries:
  "Jyostna" => 80
  "Suresh"  => 87
  "Hemanth" => 98
  "Ravi"    => 85

In [80]:
delete(studentgrades, "Raghu") # can't do this

LoadError: UndefVarError: `delete` not defined

In [82]:
d1 = Dict("a" => 5, "b" => 6)

Dict{String, Int64} with 2 entries:
  "b" => 6
  "a" => 5

In [83]:
d2 = Dict("c" => 8, "d" => 9)

Dict{String, Int64} with 2 entries:
  "c" => 8
  "d" => 9

In [84]:
# merge 2 dicts

In [85]:
merge(d1, d2)

Dict{String, Int64} with 4 entries:
  "c" => 8
  "b" => 6
  "a" => 5
  "d" => 9

In [86]:
d1 = Dict("a" => 5, "b" => 6, "c" => 8); d2 = Dict("c" => 8, "d" => 9)

Dict{String, Int64} with 2 entries:
  "c" => 8
  "d" => 9

In [87]:
merge(d1,d2)

Dict{String, Int64} with 4 entries:
  "c" => 8
  "b" => 6
  "a" => 5
  "d" => 9

In [88]:
mergewith(+, d1, d2) # if there are duplicates then they will add

Dict{String, Int64} with 4 entries:
  "c" => 16
  "b" => 6
  "a" => 5
  "d" => 9

# Range

In [89]:
1:10

1:10

In [90]:
a = 1:10

1:10

In [91]:
a[1]

1

In [92]:
a[2]

2

In [93]:
typeof(a)

UnitRange{Int64}

In [94]:
collect(a)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [96]:
sizeof(a)

16

In [97]:
sizeof(collect(a)) # collect increases the memory

80

In [98]:
supertype(UnitRange)

AbstractUnitRange{T} where T<:Real

In [99]:
supertype(AbstractUnitRange)

OrdinalRange{T, T} where T

In [100]:
supertype(OrdinalRange)

AbstractRange

In [101]:
supertype(AbstractRange)

AbstractVector (alias for AbstractArray{T, 1} where T)

In [102]:
supertype(AbstractVector)

Any

In [103]:
supertypes(UnitRange)

(UnitRange, AbstractUnitRange{T} where T<:Real, OrdinalRange{T, T} where T<:Real, AbstractRange{T} where T<:Real, AbstractVector{T} where T<:Real, Any)

In [104]:
# step size
b = 1:2:20 # start from 1, end 20, increase by 2

1:2:19

In [105]:
collect(b)

10-element Vector{Int64}:
  1
  3
  5
  7
  9
 11
 13
 15
 17
 19

In [106]:
# decreasing range

In [107]:
c = 20:-2:1

20:-2:2

In [109]:
-3.0:0.1:0.3

-3.0:0.1:0.3

In [110]:
range(start=1, step=2, stop=20)

1:2:19

In [111]:
range(5, stop=20)

5:20

In [114]:
range(-3,3,step=2)

-3:2:3

In [115]:
LinRange(10,900,100)

100-element LinRange{Float64, Int64}:
 10.0, 18.9899, 27.9798, 36.9697, 45.9596, …, 873.03, 882.02, 891.01, 900.0

# Arrays 

In [116]:
# Same as lists in python

In [117]:
arr = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [122]:
arr1 = [1,"Hemanth",2.3]

3-element Vector{Any}:
 1
  "Hemanth"
 2.3

In [123]:
typeof(arr1)

Vector{Any} (alias for Array{Any, 1})

In [124]:
arr1[1]

1

In [125]:
arr1[1:3]

3-element Vector{Any}:
 1
  "Hemanth"
 2.3

In [139]:
arr1[1:end]

4-element Vector{Any}:
 1
  "Hemanth"
 2.3
 5

In [140]:
arr[:]

3-element Vector{Int64}:
 1
 2
 3

In [143]:
arr1[3:4] = [4,8]

2-element Vector{Int64}:
 4
 8

In [144]:
arr1

4-element Vector{Any}:
 1
  "Hemanth"
 4
 8

In [128]:
# add elements to array
push!(arr1, 5)

4-element Vector{Any}:
 1
  "Hemanth"
 2.3
 5

In [153]:
# append another array
append!(arr1, [9,10])

6-element Vector{Any}:
  1
   "Hemanth"
  4
  8
  9
 10

In [154]:
arr1

6-element Vector{Any}:
  1
   "Hemanth"
  4
  8
  9
 10

In [157]:
# delete element at given index
deleteat!(arr1, 6)

5-element Vector{Any}:
 1
  "Hemanth"
 4
 8
 9

In [158]:
deleteat!(arr1, [2,3])

3-element Vector{Any}:
 1
 8
 9

In [160]:
pop!(arr1) # delete last element

9

In [161]:
arr1

2-element Vector{Any}:
 1
 8

In [162]:
# insert new element at given index
insert!(arr1,1,2) # insert 2 at index 1

3-element Vector{Any}:
 2
 1
 8

In [163]:
# same as str.split in python.
str = "Julia, Python"
split(str,",")

2-element Vector{SubString{String}}:
 "Julia"
 " Python"

In [130]:
# create same type of array

In [131]:
arr3 = Float64[2.3,4.5,6.7]

3-element Vector{Float64}:
 2.3
 4.5
 6.7

In [132]:
arr3[3] = 3

3

In [133]:
arr3 # automaticlly converted to float

3-element Vector{Float64}:
 2.3
 4.5
 3.0

In [135]:
arr4 = [1,2,"Hemanth",[2,3,4]]

4-element Vector{Any}:
 1
 2
  "Hemanth"
  [2, 3, 4]

In [136]:
arr4[4]

3-element Vector{Int64}:
 2
 3
 4

In [137]:
arr4[4][1]

2

In [118]:
arr2 = [[1,2,3],[4,5,6]]

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [4, 5, 6]

In [120]:
typeof(arr)

Vector{Int64} (alias for Array{Int64, 1})

In [121]:
typeof(arr2)

Vector{Vector{Int64}} (alias for Array{Array{Int64, 1}, 1})

In [145]:
# check elements in array

In [146]:
4 ∈ arr1

true

In [147]:
issubset(arr1, arr2)

false

In [148]:
issubset([4,8], arr1)

true

In [149]:
[4,8] ⊆ arr1 # \subseteq TAB same as above

true

In [150]:
[4,8] ⊊ arr1 # \subsetneq TAB 

true

In [152]:
arr1 ⊇ [4,8] # \supseteq TAB superset

true

# Vectors and arrays

In [1]:
[1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [2]:
[1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [4]:
[1 2 3
4 5 6
7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
mtr = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [6]:
ndims(mtr)

2

In [7]:
size(mtr)

(3, 3)

In [8]:
size(mtr,1)

3

In [9]:
size(mtr,2)

3

In [10]:
length(mtr)

9

### indexing and slicing

In [13]:
mtr

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [11]:
mtr[1]

1

In [12]:
mtr[2]

4

In [14]:
mtr[1,1]

1

In [15]:
mtr[1,2]

2

In [16]:
mtr[1,3]

3

In [17]:
row = 2
col = 1
mtr[row, col]

4

In [18]:
mtr[1:2,1:2]

2×2 Matrix{Int64}:
 1  2
 4  5

In [19]:
# get second row
mtr[2,:]

3-element Vector{Int64}:
 4
 5
 6

In [20]:
# get second column
mtr[:,2]

3-element Vector{Int64}:
 2
 5
 8

In [21]:
col1 = [1,2,3]
col2 = [4,5,6]
col3 = [7,8,9]

3-element Vector{Int64}:
 7
 8
 9

In [23]:
hcat(col1,col2,col3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [24]:
vcat(col1,col2,col3)

9-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7
 8
 9

In [26]:
mtr2 = [11 12 13; 14 15 16; 17 18 19]

3×3 Matrix{Int64}:
 11  12  13
 14  15  16
 17  18  19

In [28]:
hcat(mtr, mtr2)

3×6 Matrix{Int64}:
 1  2  3  11  12  13
 4  5  6  14  15  16
 7  8  9  17  18  19

In [29]:
vcat(mtr, mtr2)

6×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 11  12  13
 14  15  16
 17  18  19

In [30]:
[mtr; mtr2]

6×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 11  12  13
 14  15  16
 17  18  19

In [34]:
[mtr 
mtr2]

6×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 11  12  13
 14  15  16
 17  18  19

In [33]:
[mtr mtr2]

3×6 Matrix{Int64}:
 1  2  3  11  12  13
 4  5  6  14  15  16
 7  8  9  17  18  19

In [32]:
[mtr, mtr2]

2-element Vector{Matrix{Int64}}:
 [1 2 3; 4 5 6; 7 8 9]
 [11 12 13; 14 15 16; 17 18 19]

### using datatypes in matrix

In [35]:
# create empty matrix
emptymat = Matrix(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [37]:
Matrix{Any}(undef, 2, 3)

2×3 Matrix{Any}:
 #undef  #undef  #undef
 #undef  #undef  #undef

In [38]:
Matrix{Float64}(undef, 2, 3)

2×3 Matrix{Float64}:
 1.38355e-311  1.38356e-311  1.38356e-311
 1.38355e-311  1.38356e-311  1.38356e-311

In [39]:
Matrix{Int64}(undef, 2, 3)

2×3 Matrix{Int64}:
 2800365864528  140727078084752  140727076715744
 2800373959392  140727162278880  140727162278880

In [40]:
# accept 2 datatypes
Matrix{Union{Int64, String}}(undef, 3, 4)

3×4 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [41]:
# accept 2 datatypes
mtr3 = Matrix{Union{Int64, String}}(undef, 3, 4)

3×4 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef

In [42]:
mtr3[2,3] = 99

99

In [44]:
mtr3

3×4 Matrix{Union{Int64, String}}:
 #undef  #undef  #undef  #undef
 #undef  #undef   99     #undef
 #undef  #undef  #undef  #undef

In [45]:
# insert first element
mtr3[1,1] = 1

1

In [46]:
# insert second element
mtr3[1,2]  = 2

2

In [47]:
mtr3

3×4 Matrix{Union{Int64, String}}:
   1       2     #undef  #undef
 #undef  #undef   99     #undef
 #undef  #undef  #undef  #undef

In [48]:
# insert multiple elements
mtr3[2:3,1:2] = [3 4; 5 6]

2×2 Matrix{Int64}:
 3  4
 5  6

In [49]:
mtr3

3×4 Matrix{Union{Int64, String}}:
 1  2  #undef  #undef
 3  4   99     #undef
 5  6  #undef  #undef

In [50]:
mtr3[1,3] = "Hemanth"

"Hemanth"

In [51]:
mtr3

3×4 Matrix{Union{Int64, String}}:
 1  2     "Hemanth"  #undef
 3  4   99           #undef
 5  6  #undef        #undef

In [52]:
# you can't insert floats since it accepts only int and string
mtr3[1,4] = 3.4

LoadError: MethodError: Cannot `convert` an object of type 
  Float64 to an object of type 
  Union{Int64, String}

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:64


In [53]:
# None in python is equal to nothing in Julia

In [54]:
nothing

In [55]:
typeof(nothing)

Nothing

In [57]:
Matrix{Any}(nothing, 2,3)

2×3 Matrix{Any}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [58]:
Matrix{Int64}(nothing,2,3) # you can't do this

LoadError: MethodError: Cannot `convert` an object of type Nothing to an object of type Int64

Closest candidates are:
  convert(::Type{T}, ::Ptr) where T<:Integer
   @ Base pointer.jl:23
  convert(::Type{T}, ::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, ::Number) where T<:Number
   @ Base number.jl:7
  ...


In [59]:
Matrix{Union{Nothing, Int64}}(nothing,2,3)

2×3 Matrix{Union{Nothing, Int64}}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [60]:
# same for missing as well
missing

missing

In [61]:
typeof(missing)

Missing

In [62]:
Matrix{Union{Missing, Int64}}(missing,2,3)

2×3 Matrix{Union{Missing, Int64}}:
 missing  missing  missing
 missing  missing  missing

In [63]:
# you can reshape arrays
reshape(mtr3,4,3)

4×3 Matrix{Union{Int64, String}}:
 1   4           #undef
 3   6           #undef
 5    "Hemanth"  #undef
 2  99           #undef

In [64]:
reshape(1:15, 3,5)

3×5 reshape(::UnitRange{Int64}, 3, 5) with eltype Int64:
 1  4  7  10  13
 2  5  8  11  14
 3  6  9  12  15

In [65]:
# create random arrays
zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [66]:
rand(2,3)

2×3 Matrix{Float64}:
 0.547817  0.957431  0.350146
 0.778465  0.848008  0.703839

In [72]:
rand(1:20,2,3)

2×3 Matrix{Int64}:
 8  15  20
 1  19   3

In [73]:
randn(3,5)

3×5 Matrix{Float64}:
  2.18319    1.53247  -0.215046   0.617458  -0.786249
  1.06881   -1.0987   -0.741907   0.655375   0.375681
 -0.868409   1.05539  -1.59242   -0.706403   1.10305

In [67]:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [68]:
ones(Int32,2,3)

2×3 Matrix{Int32}:
 1  1  1
 1  1  1

In [69]:
trues(2,2)

2×2 BitMatrix:
 1  1
 1  1

In [70]:
falses(2,2)

2×2 BitMatrix:
 0  0
 0  0

In [71]:
fill(3.4, 3,2)

3×2 Matrix{Float64}:
 3.4  3.4
 3.4  3.4
 3.4  3.4

In [74]:
m1 = reshape(range(12.,23.,length=12), 4,3)

4×3 reshape(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, 4, 3) with eltype Float64:
 12.0  16.0  20.0
 13.0  17.0  21.0
 14.0  18.0  22.0
 15.0  19.0  23.0

In [75]:
m2 = similar(m1) # copy the structure of the m1

4×3 Matrix{Float64}:
 4.24399e-314  6.36599e-314  1.6976e-313
 4.24399e-314  8.48798e-314  1.6976e-313
 4.24399e-314  1.061e-313    1.9098e-313
 4.24399e-314  1.4854e-313   1.9098e-313

## Multi dimensional array

In [77]:
# Array{T}
Array{Float64, 3}(undef, 5,4,3)

5×4×3 Array{Float64, 3}:
[:, :, 1] =
 5.0e-324  5.0e-324  0.0       5.0e-324
 5.0e-324  1.0e-323  5.0e-324  5.0e-324
 5.0e-324  5.0e-324  5.0e-324  5.0e-324
 1.0e-323  4.4e-323  5.0e-324  5.0e-324
 5.0e-324  5.0e-324  5.0e-324  5.0e-324

[:, :, 2] =
 5.0e-324  5.0e-324  5.0e-324  5.0e-324
 5.0e-324  5.0e-324  1.0e-323  5.0e-324
 5.0e-324  0.0       5.0e-324  5.0e-324
 5.0e-324  5.0e-324  5.0e-324  5.0e-324
 5.0e-324  5.0e-324  5.0e-324  5.0e-324

[:, :, 3] =
 5.0e-324  5.0e-324  5.0e-324  5.0e-324
 5.0e-324  5.0e-324  5.0e-324  0.0
 5.0e-324  5.0e-324  0.0       1.38459e-311
 5.0e-324  5.0e-324  5.0e-324  1.38459e-311
 5.0e-324  5.0e-324  0.0       6.95285e-310

In [78]:
Array{Union{Int64, Nothing}}(nothing, 2,3,2,3)

2×3×2×3 Array{Union{Nothing, Int64}, 4}:
[:, :, 1, 1] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 2, 1] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 1, 2] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 2, 2] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 1, 3] =
 nothing  nothing  nothing
 nothing  nothing  nothing

[:, :, 2, 3] =
 nothing  nothing  nothing
 nothing  nothing  nothing

In [79]:
Array{Union{String, Missing}}(missing,4,3,2)

4×3×2 Array{Union{Missing, String}, 3}:
[:, :, 1] =
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing

[:, :, 2] =
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing
 missing  missing  missing

In [80]:
v = Vector(1:60)
arr1 = reshape(v, 5,4,3)

5×4×3 Array{Int64, 3}:
[:, :, 1] =
 1   6  11  16
 2   7  12  17
 3   8  13  18
 4   9  14  19
 5  10  15  20

[:, :, 2] =
 21  26  31  36
 22  27  32  37
 23  28  33  38
 24  29  34  39
 25  30  35  40

[:, :, 3] =
 41  46  51  56
 42  47  52  57
 43  48  53  58
 44  49  54  59
 45  50  55  60

In [81]:
arr1[:,:,3]

5×4 Matrix{Int64}:
 41  46  51  56
 42  47  52  57
 43  48  53  58
 44  49  54  59
 45  50  55  60

In [82]:
arr1[1,1,3]

41

In [85]:
[1;2;3 ;; 5;6;7 ;; 8;9;10 ;; 11;12;13]

3×4 Matrix{Int64}:
 1  5   8  11
 2  6   9  12
 3  7  10  13

In [86]:
[1;2;3 ;; 5;6;7 ;;; 8;9;10 ;; 11;12;13]

3×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  5
 2  6
 3  7

[:, :, 2] =
  8  11
  9  12
 10  13

# Broadcasting

In [1]:
v = Vector(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [2]:
n = 7

7

In [3]:
v*7

5-element Vector{Int64}:
  7
 14
 21
 28
 35

In [4]:
v+7 # is not possible

LoadError: MethodError: no method matching +(::Vector{Int64}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:578
  +(::T, ::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
   @ Base int.jl:87
  +(::Base.TwicePrecision, ::Number)
   @ Base twiceprecision.jl:290
  ...


In [5]:
# instead you can do like this
v + repeat([n], size(v,1))

5-element Vector{Int64}:
  8
  9
 10
 11
 12

In [6]:
broadcast(+,v,n) # using broadcast function easily like this

5-element Vector{Int64}:
  8
  9
 10
 11
 12

In [7]:
v .+ n # this also does the same

5-element Vector{Int64}:
  8
  9
 10
 11
 12

In [8]:
a = [4 7 2 9 11 15]

1×6 Matrix{Int64}:
 4  7  2  9  11  15

In [9]:
b = [3 7 3 9 12 15]

1×6 Matrix{Int64}:
 3  7  3  9  12  15

In [10]:
a == b # If you compare directly

false

In [11]:
# compare a and b
a .== b

1×6 BitMatrix:
 0  1  0  1  0  1

In [12]:
mat = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [13]:
ℯ^2

7.38905609893065

In [14]:
a.^2 # using broadcast

1×6 Matrix{Int64}:
 16  49  4  81  121  225

In [15]:
exp(a)

LoadError: DimensionMismatch: matrix is not square: dimensions are (1, 6)

In [16]:
exp.(a) # use dot since it is a matrix

1×6 Matrix{Float64}:
 54.5982  1096.63  7.38906  8103.08  59874.1  3.26902e6

In [19]:
sqrt.(a)

1×6 Matrix{Float64}:
 2.0  2.64575  1.41421  3.0  3.31662  3.87298

In [18]:
.√a

1×6 Matrix{Float64}:
 2.0  2.64575  1.41421  3.0  3.31662  3.87298

In [20]:
x = [3 5 7 9 12 15]

1×6 Matrix{Int64}:
 3  5  7  9  12  15

In [21]:
2x^2 + 2x + 5

LoadError: DimensionMismatch: matrix A has dimensions (1,6), matrix B has dimensions (1,6)

In [26]:
2 .* x .^ 2 .+ 2 .* x .+ 5 # using spaces between operators is important

1×6 Matrix{Int64}:
 29  65  117  185  317  485

In [27]:
2x .^ 2 .+ 2x .+ 5 # multiplication does not require dot

1×6 Matrix{Int64}:
 29  65  117  185  317  485

In [28]:
vec = [7 22 12 13 16 21 18 76]

1×8 Matrix{Int64}:
 7  22  12  13  16  21  18  76

In [31]:
vec[[true false true false true false true false]]

4-element Vector{Int64}:
  7
 12
 16
 18

In [33]:
vec .> 20 # get all the elements that are greater than 20

1×8 BitMatrix:
 0  1  0  0  0  1  0  1

In [34]:
vec[vec .> 20] # we can do same as in python

3-element Vector{Int64}:
 22
 21
 76

In [35]:
vec .% 4

1×8 Matrix{Int64}:
 3  2  0  1  0  1  2  0

In [36]:
(vec .% 4) .== 0

1×8 BitMatrix:
 0  0  1  0  1  0  0  1

In [37]:
vec[(vec .% 4) .== 0] # get all the numbers divisible by 4

3-element Vector{Int64}:
 12
 16
 76

In [38]:
mat = rand(1:100, 200, 10)

200×10 Matrix{Int64}:
 42  75  57  62  31  81  67   2    5   42
 60  20  95  49  95  76  29  99   73    1
 52   7  42  45  62  85  56  38   49   22
 66  17  68  52  18  53  93  55   45   41
 31  35  27  56  23  92  93  13   20   49
 56  86  10  71   8  62  73  19   97   24
 56  56  64  59  52  53  34  68   83   16
 60  57  82  80  34  60  60  86   48   76
 32  77  89  19  38  95  85   5   20   49
 45  55  15  68  12  16  14  58  100   28
 15  88   8  43  64  39  57  22   99   42
 95  94   1  75  68   3  88  66   23   68
  5  44  95  48  41  90  52  47   13   27
  ⋮                   ⋮               
 40  88  86  61   6  45   3  30   84   15
 78  67  85  49  18  88  45  20   90   57
 68  66  31  26  97  69  68  91   59  100
 91  24  67  28  74  70  37  50   59   31
 60  27  14   6  97  51  69  32   81   92
 44  24   8  48  18  17  24  67   45    8
 96  93  76  95  77  58  29  98   90   24
 32   8  38  69  77  43  17  13   31  100
  7  50  54  55  94  41  95  27   69   84
  5  34  72  30

In [39]:
cond1 = mat[:, 1] .% 3 .== 0 # first column divisible by 3

200-element BitVector:
 1
 1
 0
 1
 0
 0
 0
 1
 0
 1
 1
 0
 0
 ⋮
 0
 1
 0
 0
 1
 0
 1
 0
 0
 0
 1
 1

In [40]:
cond2 = mat[:, 2] .%4 .== 0 # second column divisible by 3

200-element BitVector:
 0
 1
 0
 0
 0
 0
 1
 0
 0
 0
 1
 0
 1
 ⋮
 1
 0
 0
 1
 0
 1
 0
 1
 0
 0
 1
 0

In [42]:
cond1 .& cond2 # cond1 and cond2

200-element BitVector:
 0
 1
 0
 0
 0
 0
 0
 0
 0
 0
 1
 0
 0
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0
 1
 0

In [44]:
mat[cond1 .& cond2, :]

17×10 Matrix{Int64}:
 60   20  95  49  95  76  29  99  73   1
 15   88   8  43  64  39  57  22  99  42
 84   84  64  41  90  46  60  34  13   1
 36   64  29   4  83  29  73  47  63  16
 84   92  36  55  72  26  62  25  78  30
 45   36  36  90   1  11  72  82  89  13
 39  100  40  98  16  18  49  51  36  77
  9   88  98  47  64  12  79  91  31  50
 63   84  93  40  77   2  12  24  21  28
 42   76   8  59  93  94  83  53  53  74
 30   44  39  13  47  61  98  14  84  97
 39   68  38   8  91  39  27  63  67   7
 36   80  98   3  39  42  13   2  54  68
 48   80  74  24  91  31  29  10  34  72
 30   48  13  75  95  33   1  46  83  25
 33   64  53  36  94  51  23  37  41   6
 51   88  92  47  57  72  81   1  96  56

# sets

In [45]:
# sets are same as in python

In [48]:
s = Set([1,2,3,4])

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [49]:
Set([1,1,2,3,4])

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [50]:
Set((1,2,3,4))

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [51]:
s[1] # sets does not gave index

LoadError: MethodError: no method matching getindex(::Set{Int64}, ::Int64)

In [52]:
Set([1 2 3 4])

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [53]:
x1 = [1 2 2 3 4]
x2 = [3 5 6 6 7]

1×5 Matrix{Int64}:
 3  5  6  6  7

In [54]:
union(x1, x2) # union operation

7-element Vector{Int64}:
 1
 2
 3
 4
 5
 6
 7

In [55]:
intersect(x1, x2)

1-element Vector{Int64}:
 3

In [56]:
setdiff(x1, x2)

3-element Vector{Int64}:
 1
 2
 4

In [58]:
symdiff(Set(x1), Set(x2))

Set{Int64} with 6 elements:
  5
  4
  6
  7
  2
  1

In [59]:
issubset(x1, x2)

false

In [62]:
x1 ⊆ x2

false

# Basic Linear Algebra

In [63]:
using LinearAlgebra

In [64]:
mat = [1 4 8; 2 5 9; 3 6 7]

3×3 Matrix{Int64}:
 1  4  8
 2  5  9
 3  6  7

In [65]:
tr(mat) # trace of matrix (sum of diagonal entries)

13

In [66]:
det(mat)

9.0

In [67]:
# transpose of a matrix
transpose(mat)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 1  2  3
 4  5  6
 8  9  7

In [69]:
mat' # same as above

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 1  2  3
 4  5  6
 8  9  7

In [70]:
mat2 = [4 2 1; 5 0 3; 3 2 1]

3×3 Matrix{Int64}:
 4  2  1
 5  0  3
 3  2  1

In [71]:
mat * mat2 # this is not correct

3×3 Matrix{Int64}:
 48  18  21
 60  22  26
 63  20  28

In [72]:
mat .* mat2 # this is actual 

3×3 Matrix{Int64}:
  4   8   8
 10   0  27
  9  12   7

In [73]:
x = 7.6;
y = 1 / x # y is inverse if x

0.13157894736842105

In [74]:
# identity matrix
idt = [1 0 0; 0 1 0; 0 0 1] 

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [75]:
I # inbuilt identity matrix

UniformScaling{Bool}
true*I

In [76]:
I(3)

3×3 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅
 ⋅  1  ⋅
 ⋅  ⋅  1

In [78]:
idt == I(3)

true

In [80]:
# inverse of a matrix
invmat = inv(mat)

3×3 Matrix{Float64}:
 -2.11111    2.22222   -0.444444
  1.44444   -1.88889    0.777778
 -0.333333   0.666667  -0.333333

In [82]:
mat * invmat

3×3 Matrix{Float64}:
  1.0          0.0          -4.44089e-16
  0.0          1.0          -4.44089e-16
 -8.88178e-16  8.88178e-16   1.0

In [83]:
# matrix divison
A = [1 2; 2 -4]

2×2 Matrix{Int64}:
 1   2
 2  -4

In [85]:
B = [28; -2]

2-element Vector{Int64}:
 28
 -2

In [87]:
# A * X = B
X = A\B

2-element Vector{Float64}:
 13.5
  7.25

In [88]:
A*X == B

true