In [6]:
struct rect_prism
    width::Real
    length::Real
    height::Real
end

In [7]:
pr = rect_prism(34,45,2.3)

rect_prism(34, 45, 2.3)

In [8]:
volume = pr.length * pr.width * pr. height

3518.9999999999995

In [9]:
# exercise 2

In [10]:
myint = 42

42

In [12]:
myfloat = float(myint)

42.0

In [13]:
# exercise 3

In [14]:
name = "Aurther"; weight = 75; height = 1.80

1.8

In [17]:
bmi = round(weight/height^2,digits=2)

23.15

In [22]:
println("Hello $name. You are $weight kg and $height m. Your BMI is $bmi.")

Hello Aurther. You are 75 kg and 1.8 m. Your BMI is 23.15.


In [1]:
# exercise 4

In [2]:
X = rand(Float64, 100, 3)

100×3 Matrix{Float64}:
 0.189325     0.497068   0.523771
 0.256138     0.646683   0.779584
 0.488227     0.0905899  0.52417
 0.72855      0.415729   0.118452
 0.643521     0.470989   0.924573
 0.638423     0.878913   0.231745
 0.857224     0.220467   0.278382
 0.234823     0.790308   0.407226
 0.75134      0.32033    0.256519
 0.952257     0.720575   0.979473
 0.104464     0.686078   0.115914
 0.581251     0.552982   0.358933
 0.267491     0.932311   0.561386
 ⋮                       
 0.625408     0.661052   0.920278
 0.896567     0.766772   0.110198
 0.000606568  0.864629   0.280648
 0.249079     0.36497    0.72974
 0.624099     0.722645   0.949654
 0.555428     0.556609   0.366189
 0.419716     0.10091    0.648129
 0.353068     0.432833   0.0916853
 0.493852     0.102624   0.0699993
 0.612623     0.177158   0.375382
 0.850411     0.523747   0.412288
 0.557136     0.618535   0.420551

In [3]:
y = rand(100)

100-element Vector{Float64}:
 0.13245054676063883
 0.3511233507421535
 0.43467759088188906
 0.2616202160588499
 0.9529141487395775
 0.7085737548198857
 0.22573464164789747
 0.8656415553155428
 0.19689306191486988
 0.7969163870847084
 0.5854864476369597
 0.6475441047099669
 0.011343762133077195
 ⋮
 0.13454468112037998
 0.1557390291006916
 0.27115958045841815
 0.21997574750892612
 0.3830530186649894
 0.4070839161054124
 0.26583405445889063
 0.09430578062192829
 0.05791873185465213
 0.1795280029535593
 0.942790026110564
 0.27200138570828003

In [11]:
# Add constant
X = [ones(100) X]

100×4 Matrix{Float64}:
 1.0  0.189325     0.497068   0.523771
 1.0  0.256138     0.646683   0.779584
 1.0  0.488227     0.0905899  0.52417
 1.0  0.72855      0.415729   0.118452
 1.0  0.643521     0.470989   0.924573
 1.0  0.638423     0.878913   0.231745
 1.0  0.857224     0.220467   0.278382
 1.0  0.234823     0.790308   0.407226
 1.0  0.75134      0.32033    0.256519
 1.0  0.952257     0.720575   0.979473
 1.0  0.104464     0.686078   0.115914
 1.0  0.581251     0.552982   0.358933
 1.0  0.267491     0.932311   0.561386
 ⋮                            
 1.0  0.625408     0.661052   0.920278
 1.0  0.896567     0.766772   0.110198
 1.0  0.000606568  0.864629   0.280648
 1.0  0.249079     0.36497    0.72974
 1.0  0.624099     0.722645   0.949654
 1.0  0.555428     0.556609   0.366189
 1.0  0.419716     0.10091    0.648129
 1.0  0.353068     0.432833   0.0916853
 1.0  0.493852     0.102624   0.0699993
 1.0  0.612623     0.177158   0.375382
 1.0  0.850411     0.523747   0.412288
 1.0  0.55

In [12]:
β = ((X' * X) .^ -1) * X' * y # This is not correct

4-element Vector{Float64}:
 1.7658920451216096
 3.586056238434308
 2.9918445028393745
 3.3013546751088243

In [13]:
β = inv(X'X)X'y

4-element Vector{Float64}:
  0.4260438937130006
  0.06659777030616376
 -0.0166665333682205
 -0.014674973834428106